FROM nginx:alpine

COPY . /usr/share/nginx/html

RUN echo "events {} http { include mime.types; server { listen 80; location / { root /usr/share/nginx/html; index index.html index.htm; } } }"> /etc/nginx/nginx.conf
