services:
  nginx:
    build: .
    ports:
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - bluelight
  your_app:
    image: bluelight